spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/database1?serverTimezone=UTC&useLegacyDatetimeCode=false"
    username: "root"
    password: "Sqw2230329asd"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        jdbc:
          time_zone: UTC